version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - ./src:/var/www/html

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootsecret
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: wordpressdb
    volumes:
      - ./db:/var/lib/mysql